- name: setup security
  include_role:
    name: security
  when: security == "kerberos"

- name: create property
  vars:
    url: "{{ urls[security].url }}"
  copy:
    dest: "{{ srcdir }}/ci/system-test/src/main/resources/schema-registry.properties"
    content: |
      security={{ "kerberos" if security == "kerberos" else "" }}
      registry.urls={{ url }}
      schema.registry.client.ssl.protocol=SSL
      schema.registry.client.ssl.trustStoreType=JKS
      schema.registry.client.ssl.trustStorePath=/tmp/registry.client.truststore.jks
      schema.registry.client.ssl.trustStorePassword=cli123

- name: run test {{ security }}
  vars:
    url: "{{ urls[security].url }}"
  command: >
    mvn -batch-mode
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    -Drat.skip=true
    clean test
  args:
    chdir: "{{ srcdir }}/ci/system-test"
