- name: helm install postgresql
  command: >
    helm install stable/postgresql
        --name psql
        --set postgresqlUsername=registry,postgresqlPassword=registry,postgresqlDatabase=registry,persistence.enabled=false
        --tiller-namespace={{ tiller_namespace }}
        --set "db.user=registry,db.password=registry,db.name=registry,replication.enabled=false,master.persistence.enabled=false"
        --wait