- name: create krb5.conf
  vars:
  copy:
    dest: "/etc/krb5.conf"
    content: |
      [libdefaults]
        renew_lifetime = 7d
        forwardable = true
        default_realm = K8S.COM
        ticket_lifetime = 24h
        dns_lookup_realm = false
        dns_lookup_kdc = false
        allow_weak_crypto = false
        clockskew = 300
        rdns = false
        udp_preference_limit = 1
      [logging]
        default = CONSOLE
        admin_server = CONSOLE
        kdc = CONSOLE
      [realms]
        K8S.COM = {
          admin_server = kdc.{{ namespace }}.svc.cluster.local
          kdc = kdc.{{ namespace }}.svc.cluster.local
        }
  when: zuul is defined

- name: copy client truststore
  command: >
    cp ci/ssl/registry.client.truststore.jks /tmp/registry.client.truststore.jks
  args:
    chdir: "{{ srcdir }}"

- name: remove keytab
  command: >
    rm -f /tmp/alice.keytab
  args:
    chdir: "{{ srcdir }}"

- name: fetch keytab
  command: >
    {{ mit_kerberos }}/kadmin -p 'admin/admin' -w Hortonworks -q 'ktadd -norandkey -k /tmp/alice.keytab alice'
  args:
    chdir: "{{ srcdir }}"

- name: kdestroy
  command: >
    {{ mit_kerberos }}/kdestroy
  args:
    chdir: "{{ srcdir }}"

- name: kinit
  command: >
    {{ mit_kerberos }}/kinit -kt /tmp/alice.keytab alice
  args:
    chdir: "{{ srcdir }}"
